storage = 'DB'

[origins]
allowedOrigins = ["http://localhost:3000"]

[devportal.store]
host = "devportal-postgres"
port = 5432
user = "postgres"
password = "postgres"
database = "devportal"

[devportal.models]
awsAccessKeyId = ""
awsSecretAccessKey = ""
awsRegion = ""

